### PR TITLE
Added math module

### PR DESCRIPTION
**Pull request by zalanwastaken**
### Notes
I added a *math* module that has useful math function not included in *love2d* or *Lua*.
Also updated the *lib.lua* file to include the math module

### CODE REVIEW

**Comment by zalanwastaken** [comment]
# Closed because of no response

**Comment by Nykenik24** [comment]
Sorry for no response. I was a lil' busy, but thanks for the contribution! I really liked the module!

I really didn't expect to have pull requests this soon, this is my first _real_ project and i am not experienced with these things. I will try to answer other pull requests and issues, and again i'm so sorry for not answering.

**Comment by Nykenik24** [comment]
Do you grant me permission to add the code of the module (or maybe some functions) to the library?

**Comment by zalanwastaken** [comment]
### Hey there!  

No worries at all; life gets busy, and it's completely understandable. We're just excited to see you diving into your first real project—congrats on that! 🎉  

It's awesome to hear that you liked the module! Don't stress about not having all the answers right now; everyone starts somewhere.  

Take your time reviewing pull requests and addressing issues—it’s all part of the learning curve. And remember, the community is here to support you, so don’t hesitate to reach out if you ever need help navigating this process.  

Keep up the amazing work, and no need to apologize. You're doing great! 😊  

Also, this was my first pull request, so I’m just as excited as you are! 😄

**Pull request closed without merging**
